auto inject Vimium C for #218
EdgeTranslate/EdgeTranslate pull request #225
Opened 2021-07-05 18:18 UTC by gdh1995

### describe the bug/feature 解决的问题或新增的功能

This commit tries injecting Vimium C to inner PDF Viewer.

### summary of code change 描述发生的改变

It loads Vimium C's `lib/injector.js` on `static/pdf/viewer.html` loading, so that Vimium C will run on it.

It prefers the version of Vimium C on Edge Add-ons on MS Edge; while on Chrome it prefers the version on Chrome Web Store.

This commit only affects the PDF Viewer page, but not options page.
If there's a new text option to let users type an extension ID, then `static/pdf/vimium-c-injector.js` will use it.

2021-07-05 18:25 UTC, gdh1995 commented
顺利的话，安装 EdgeTranslate 和 Vimium C，并打开 pdf 文件后，点击右上角的 Vimium C 图标将能看到：
![image](https://user-images.githubusercontent.com/5547703/124507655-ccaa2100-de00-11eb-86b7-4d7ef248c477.png)

点击“信任此扩展”后，当前页面应该会自动刷新，然后就能用 Vimium C 快捷键了。

----

添加了一个 `vimiumExtensionInjector` 的字符串配置项，默认自动根据浏览器是新版 Edge 还是其它来加载对应商店版本的 Vimium C。如果用户没安装的话就会有个 `<script>` 加载失败的报错。

所以可以改掉 `vimium-c-injector.js` 来跳过空值，或者在设置页面里加开关/文本框来动态启用这个。我不熟悉 EdgeTranslate 设置页面的设计，就不贸然修改了。

2021-07-06 02:24 UTC, nickyc975 commented on static/pdf/vimium-c-injector.js
> +        const str = channelElement.textContent
1. 这一行，以及前面的第45, 50这两行，是不是少了分号？

2021-07-06 02:25 UTC, nickyc975 commented on static/pdf/vimium-c-injector.js
> +        box.classList.contains("pdfPresentationMode")
这一行是不是没用的，应该删除？

2021-07-06 02:39 UTC, nickyc975 commented on src/manifest_chrome.json
> +    "content_security_policy": "script-src 'self' 'unsafe-eval' chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/ chrome-extension://aibcglbfblnogfjhbcmmpobjhnomhcdo/; object-src 'self'",
另外我比较好奇的一点是，如果这里改成chrome-extensions://* 是不是就可以允许将任意扩展注入到侧边翻译的内置pdf viewer里了？

2021-07-06 02:42 UTC, gdh1995 commented on src/manifest_chrome.json
> +    "content_security_policy": "script-src 'self' 'unsafe-eval' chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/ chrome-extension://aibcglbfblnogfjhbcmmpobjhnomhcdo/; object-src 'self'",
我没尝试过，等会试试。其它地方在改了

2021-07-06 02:54 UTC, Mark-Fenng commented on static/pdf/vimium-c-injector.js
> +        const str = channelElement.textContent
format相关的也可以在咱们merge之后处理

2021-07-06 03:03 UTC, gdh1995 commented on src/manifest_chrome.json
> +    "content_security_policy": "script-src 'self' 'unsafe-eval' chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/ chrome-extension://aibcglbfblnogfjhbcmmpobjhnomhcdo/; object-src 'self'",
报错 `Ignored insecure CSP value "chrome-extension://*/" in directive 'script-src'`。看起来不行

2021-07-06 03:06 UTC, nickyc975 commented on src/manifest_chrome.json
> +    "content_security_policy": "script-src 'self' 'unsafe-eval' chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/ chrome-extension://aibcglbfblnogfjhbcmmpobjhnomhcdo/; object-src 'self'",
好的，谢谢你的贡献！

2021-07-06 03:09 UTC, gdh1995 commented
呃抱歉昨晚上我没 wifi，我就没装 node_modules，没注意到 eslint 和 commitlint。新的提交按规则来了

2021-07-06 03:32 UTC, Mark-Fenng commented on static/pdf/vimium-c-injector.js
> +        if (injectorURL === "nul" || injectorURL === "/dev/null") {
这里的 "nul"麻烦确认一下是不是一个typo

2021-07-06 03:37 UTC, gdh1995 commented on static/pdf/vimium-c-injector.js
> +        if (injectorURL === "nul" || injectorURL === "/dev/null") {
不是，只是我沿用了写bat/bash脚本的习惯，约定这两种值表示“空”罢了。目的是提供一个方式来停止注入脚本。当然由于网页 JS 环境里基本上没有文件路径的概念，这俩常量也可以只用一个常量代替，或者换成别的。

2021-07-06 03:38 UTC, gdh1995 commented on static/pdf/vimium-c-injector.js
> +        if (injectorURL === "nul" || injectorURL === "/dev/null") {
MS CMD 的 bat 脚本里“不存在的文件”是 `nul` 表示，Linux 脚本里用 `/dev/null` 。

2021-07-06 03:40 UTC, Mark-Fenng commented
![image](https://user-images.githubusercontent.com/27533910/124538772-c2167880-de4e-11eb-938e-ded378ba30c4.png)
如果没有安装vimium-c的话，这里是不是可以麻烦再处理一下

2021-07-06 04:02 UTC, gdh1995 commented
改了。

2021-07-06 06:29 UTC, Mark-Fenng requested changes

2021-07-06 06:29 UTC, Mark-Fenng commented on src/manifest_firefox.json
> +    "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
火狐上没有办法使用pdf.js，所以这里对firefox的CSP修改是不需要的？

2021-07-06 06:41 UTC, gdh1995 commented on src/manifest_firefox.json
> +    "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
这一行之前在基础的 `manifest.json` 里，结果 `manifest_chrome.json` 里的 CSP 就没法覆盖它，所以我挪了一下。

这一行去掉的话 firefox 版本就和之前版本的编译结果不一样了。如果在 PDF 页面之外的地方也用到了 `'unsafe-eval'`，那就还是留着吧。

2021-07-06 06:51 UTC, Mark-Fenng commented on src/manifest_firefox.json
> +    "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
基础manifest.json是chrome与firefox公共的部分，因为这次的更改只对pdf.js做了修改，而在build firefox版本时，不会包含pdf.js部分，所以去掉这里的CSP才能保证咱不会对火狐的版本产生影响？

2021-07-06 07:25 UTC, Mark-Fenng commented on src/manifest_firefox.json
> +    "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
不好意思，是我的错

2021-07-06 07:25 UTC, Mark-Fenng approved these changes

2021-07-07 05:22 UTC, nickyc975 approved these changes

2021-07-07 05:44 UTC, merged

2021-07-28 10:11 UTC, gdh1995 commented
Hello, I find the hook `window.VApi.$` in `static/pdf/vimium-c-injector.js` needs to be updated. How should I do this? Another PR, or I just put new code here and some of you maintainers apply it ?

The main places to fix are:
1. The old `VApi.$` may need more arguments, so replace `oldScroll.call(...)` with `oldScroll.apply(this, arguments);`
2. change the function from lambda to `function (element, ...` to make `arguments` avaliable.

2021-07-28 10:17 UTC, Mark-Fenng commented
It would be perfect if you're willing to pull a request😀